.\" Copyright (c) 2022 Vadim Vygonets <vadik@vygo.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd 3 February 2022
.Dt XSSSUSPEND 1 LOCAL
.Os
.Sh NAME
.Nm xsssuspend
.Nd suspend X screen saver
.Sh SYNOPSIS
.Nm
.Op Ar command Op Ar argument ...
.Sh DESCRIPTION
.Nm
suspends the X screen saver and DPMS timer for the duration of its runtime.
After
.Nm
terminates for any reason or is disconnected from the X server,
the timers are restarted, unless suspended by another client.
.Pp
If no command is given,
.Nm
will wait indefinitely until it's terminated by a signal.
It's meant to be killed by a keyboard interrupt (normally
.Li Control-C ) .
.Pp
If a command is given,
.Nm
runs the command and exits after it's finished,
or immediately if execution fails.
.Sh EXAMPLES
.Bl -tag -width indent
.It Li "xsssuspend telnet towel.blinkenlights.nl"
Watch Star Wars in the terminal,
suspending the screen saver for the duration of the film.
.El
.Sh DIAGNOSTICS
.Nm
exits 0 on success, 127 if
.Xr exec 3
fails and 1 if another error occurs.
.Pp
Being killed by
.Dv SIGINT
(keyboard interrupt) or
.Dv SIGTERM
(termination) signal is not considered an error.
Exit status of the command is not propagated.
.Sh SEE ALSO
.Xr XScreenSaverSuspend 3 ,
.Xr xset 1
.Sh AUTHORS
.An Vadim Vygonets Aq vadik@vygo.net
.Sh BUGS
.Nm
does not detect disconnection from the X server,
and will hang until it's killed.
