.\" Copyright (c) 2022 Vadim Vygonets <vadik@vygo.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd 26 March 2022
.Dt XSSSUSPEND 1 LOCAL
.Os
.Sh NAME
.Nm xsssuspend
.Nd suspend X screen saver
.Sh SYNOPSIS
.Nm
.Op Ar command Op Ar argument ...
.Sh DESCRIPTION
.Nm
suspends the X screen saver and DPMS timer for the duration of its runtime.
After it
terminates for any reason or is disconnected from the X server,
the timers are restarted, unless suspended by another client.
.Pp
.Nm
shuts down the X server connection and exits with status 0
if it receives the
.Dv SIGTERM
(termination) signal.
If no command is given,
.Dv SIGINT
(keyboard interrupt, normally
.Li Control-C )
is handled in the same manner.
.Pp
If a command is given,
.Nm
runs the command and exits after it's finished,
or immediately if execution fails.
.Dv SIGINT
is ignored in this mode, delegating its handling to the child process.
.Pp
If initialisation fails,
.Nm
exits immediately.
It wakes up once per hour to check its connection to the X server,
and exits on any X error.
.Sh EXAMPLES
.Bl -tag -width indent
.It Li "xsssuspend telnet towel.blinkenlights.nl"
Watch Star Wars in the terminal,
suspending the screen saver for the duration of the film.
.El
.Sh DIAGNOSTICS
.Nm
exits 0 if killed by
.Dv SIGINT
or
.Dv SIGTERM ,
126 if
.Xr exec 3
fails and 127 if another error occurs.
If the child process exits,
.Nm
propagates its exit status.
If the child process is terminated by a signal,
.Nm
exits 128 plus the signal number.
.Sh SEE ALSO
.Xr XScreenSaverSuspend 3 ,
.Xr xset 1
.Sh AUTHORS
.An Vadim Vygonets Aq vadik@vygo.net
